# -*- coding: utf-8 -*-
"""linear_regression_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yxivAu5GCr23RwSTClaQw94aFkvrRmgW
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Aim is to predict the marks of students of the test data

# Use the file namd 'training data' to train the model

data = pd.read_excel('Training data.xlsx')
x_train = np.array(data.iloc[:,0:8])
y_train = np.array(data.iloc[:,8]).reshape(-1,1)

# Try plotting y_train with different features
# To get an idea whether to add some features or not
# Add some features if required in x_train
# Also do label encoding for features not represented in numbers
# refer the link if not know : https://youtu.be/589nCGeWG1w?si=t2Wa7LgbUOO4RooM

def feature_changing(x_train):
  x_train[:,0] = (x_train[:,0]=='no')*1
  x_train[:,1] = (x_train[:,1]=='M')*1
  return x_train

x_train = feature_changing(x_train)

def z_score(x_train):
  x_std = x_train.std(axis=0)
  x_mean = x_train.mean(axis=0)
  x_train = (x_train - x_mean)/x_std
  return x_train,x_std,x_mean

def cost(x_train,y_train,w,b):
  predict_y = x_train@w + b
  loss = ((predict_y - y_train)**2).sum()/(2*x_train.shape[0])
  return loss

def gradient_descent(x_train,y_train,w,b):
  lr = 0.0001
  n_samples = x_train.shape[0]
  for i in range(n_samples):
      xi = x_train[i,:].reshape(-1,1)  # shape (n_features, 1) 
      yi = y_train[i]  # scalar
      error = (xi.T @ w + b)[0] - yi          # scalar
      w -= lr * xi * error             # shape (n_features, 1)
      b -= lr * error
  return w, b

x_train = x_train.astype(np.float64)
x_train,x_std,x_mean = z_score(x_train)

np.random.seed(0)
w = np.random.randn(x_train.shape[1],1)
b = np.random.randn(1)

old_cost = 0

while abs(old_cost - cost(x_train,y_train,w,b))>0.00001:
  old_cost = cost(x_train,y_train,w,b)
  w,b = gradient_descent(x_train,y_train,w,b)
  print(f"Cost : {cost(x_train,y_train,w,b)}")

x_predict = pd.read_excel('Test data.xlsx').iloc[:,:8].to_numpy()
x_predict = feature_changing(x_predict)
x_predict = (x_predict - x_mean)/x_std
ans = pd.read_excel('Test data.xlsx').iloc[:,8].to_numpy()

y_predict = (np.dot(x_predict,w) + b).flatten()

accuracy = 0
for dim in range(len(ans)):
  if abs(y_predict[dim]-ans[dim])<0.5: # do not change the tolerance as you'll be checked on +- 0.5 error only
    accuracy += 0.5
ok = 'Congratulations' if accuracy>95 else 'Optimization required'
print(f"{ok}, your accuracy is {accuracy}%")